[package]
name = "vk_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0", default-features = false, features = ["linked", "debug", "std"] }
winit = { version = "0.30.5" }
ash-window = "0.13.0"
lazy_static = "1.4.0"
nalgebra-glm = "0.19.0"